'use client';
import {useEffect,useState} from 'react';
import {OneThing,Journal} from './editorial';
import {useSceneMotion} from './motion';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,Check,Play,Pause,RotateCcw,Leaf,Sparkles,BellOff,ChartNoAxesColumnIncreasing,Trophy} from 'lucide-react';
export default function Home(){
useSceneMotion();
const [running,setRunning]=useState(false),[seconds,setSeconds]=useState(1500),[done,setDone]=useState([false,true,false]);
useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[running]);
useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
useEffect(()=>{
const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:object)=>void|Promise<void>}}).modelContext;
if(!context?.registerTool)return;const lifecycle=new AbortController();
try{Promise.resolve(context.registerTool({name:'control_focus_session',title:'Управлять фокус-сессией',description:'Запускает новую 25-минутную фокус-сессию, ставит её на паузу или сбрасывает таймер.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','pause','reset']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const action=(input as {action?:unknown})?.action;if(!['start','pause','reset'].includes(String(action)))throw new Error('Допустимы start, pause, reset');flushSync(()=>{if(action==='start'||action==='reset')setSeconds(1500);setRunning(action==='start')});document.getElementById('focus')?.scrollIntoView({block:'center',behavior:'smooth'});return {action,running:action==='start'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
return()=>lifecycle.abort();
},[]);
const start=()=>{document.getElementById('focus')?.scrollIntoView({behavior:'smooth',block:'center'});setRunning(true)};
return <><header><a className="brand" href="#"><b>✳</b> тихо<sup>®</sup></a><nav><a href="#approach">Подход</a><a href="#space">Возможности</a><a href="#rhythm">Ваш ритм</a></nav><button className="outline" onClick={start}>Попробовать <ArrowUpRight size={17}/></button></header><main>
<section className="hero-track"><div className="hero"><div className="eyebrow"><i/> МЕНЬШЕ ШУМА — БОЛЬШЕ СМЫСЛА</div><h1><span className="line-mask"><span className="line-inner">Пространство</span></span><span className="line-mask"><span className="line-inner">для <em>главного</em></span></span></h1><p>Соберите мысли, задачи и внимание в одном месте.<br/>Хорошая работа начинается со спокойствия.</p><button className="primary" onClick={start}>Найти свой фокус <ArrowUpRight size={18}/></button><small className="note">25 минут для себя. Начните прямо здесь.</small>
<div className="float task-float"><small>СЕГОДНЯ В ПЛАНЕ</small><div><span className="check"><Check size={12}/></span> Оставить только важное</div><div className="muted"><span className="box"/> Дать идеям пространство</div><label>Хорошее начало ✧</label></div>
<div className="float focus-float"><span className="icon"><BellOff size={20}/></span><div><strong>Вы в потоке</strong><small>Всё остальное подождёт</small></div><i className="dot"/></div>
<div className="float chart-float"><small>Время для главного ↗</small><strong>+32<small>%</small></strong><div className="bars">{[30,44,39,65,54,80,100].map((v,i)=><i key={i} style={{height:v+'%'}}/>)}</div><small>Меньше переключений — больше ясности</small></div><span className="sculpture sculpture-blue" aria-hidden="true">✳</span><span className="sculpture sculpture-orange" aria-hidden="true">✳</span><a className="scroll" href="#approach">Листайте в своём темпе <span>↓</span></a></div></section>
<section id="approach" className="intro reveal"><span className="eyebrow">НАШ ПОДХОД</span><h2 className="editorial-heading">Не успевать <span className="soft">больше</span><br/>Успевать <span className="word-icon round"><Leaf aria-hidden="true"/></span> то, что важно</h2><p>Мы верим в работу без лишнего напряжения.<br/>Немного структуры. Место для вдохновения. И свой темп.</p></section>
<section id="space" className="bento"><article className="card tall reveal"><div><span className="index">01 / ЯСНОСТЬ</span><h3>Каждой мысли —<br/>своё место</h3><p>Разгрузите голову. Соберите главное<br/>в короткий, понятный план.</p></div><div className="task-panel"><div className="panel-title">Мой спокойный день <b>✳</b></div>{['Набросать новую идею','Прогуляться без телефона','Закончить важную задачу'].map((t,i)=><button className={'task-row '+(done[i]?'completed':'')} key={t} onClick={()=>setDone(d=>d.map((v,j)=>j===i?!v:v))}><span className={done[i]?'check':'box'}>{done[i]&&<Check size={12}/>}</span>{t}</button>)}<div className="progress-label">{done.filter(Boolean).length} из 3 завершено <span className="progress"><i style={{width:done.filter(Boolean).length/3*100+'%'}}/></span></div></div><span className="badge"><Check size={12}/> Всё под контролем</span></article>
<div className="column"><article className="card small reveal"><div className="icons"><span><Leaf size={24}/></span><i>↔</i><span><Sparkles size={24}/></span></div><h3>Бережно к себе</h3><p>Пауза — часть процесса.<br/>Оставляйте место для жизни.</p></article><article className="card small reveal"><div className="notification"><BellOff size={20}/><div><strong>Тишина включена</strong><small>Только вы и ваша задача</small></div><i className="dot"/></div><h3>Без лишнего шума</h3><p>Меньше отвлечений.<br/>Больше глубокого погружения.</p></article></div>
<article id="focus" className="card tall reveal"><div className="timer-panel"><div className="timer-top"><span><i className="dot"/> {running?'Время для главного':'Фокус-сессия'}</span><span>25 мин</span></div><div className="timer" role="timer" aria-label="Осталось времени">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</div><div className="controls"><button onClick={()=>{if(seconds===0)setSeconds(1500);setRunning(!running)}}>{running?<Pause size={14}/>:<Play size={14}/>} {running?'Пауза':seconds===0?'Ещё раз':'Начать'}</button><button className="reset" aria-label="Сбросить таймер" onClick={()=>{setSeconds(1500);setRunning(false)}}><RotateCcw size={15}/></button></div><small aria-live="polite">{seconds===0?'Отличная работа. Время отдохнуть.':running?'Вдохните. Делайте одно дело за раз.':'Одна задача. Один спокойный отрезок.'}</small></div><div><span className="index">03 / ВНИМАНИЕ</span><h3>Поймайте свой поток</h3><p>25 минут на одну задачу.<br/>Без спешки и переключений.</p></div></article></section>
<OneThing/>
<section id="rhythm" className="rhythm reveal"><span className="eyebrow">МАЛЕНЬКИЕ ШАГИ — БОЛЬШИЕ ПЕРЕМЕНЫ</span><span className="satellite rhythm-satellite" aria-hidden="true"><span className="mini-ring">25</span><small>Минут внимания</small></span><h2 className="editorial-heading">Хороший <span className="word-icon orange"><ChartNoAxesColumnIncreasing aria-hidden="true"/></span> <span className="soft">день</span><br/>складывается из простого</h2><span className="satellite trophy-satellite" aria-hidden="true"><Trophy/></span><div className="metrics"><div><strong><span data-count="1">01</span><small>задача</small></strong><p>В центре внимания</p></div><div><strong><span data-count="25">25</span><small>минут</small></strong><p>На спокойную работу</p></div><div><strong><span data-count="5">05</span><small>минут</small></strong><p>Чтобы выдохнуть</p></div></div></section>
<Journal/>
<section className="closing reveal">
<div className="closing-orbit closing-orbit-one" aria-hidden="true"/><div className="closing-orbit closing-orbit-two" aria-hidden="true"/>
<div className="closing-widget closing-task" aria-hidden="true"><span className="closing-check"><Check size={15}/></span><div><small>ГЛАВНОЕ НА СЕЙЧАС</small><strong>Закончить одну задачу</strong></div><span className="closing-done">готово</span></div>
<div className="closing-widget closing-timer" aria-hidden="true"><div className="closing-ring"><span>25</span></div><div><strong>Фокус</strong><small>одно дело за раз</small></div><i className="dot"/></div>
<div className="closing-widget closing-quiet" aria-hidden="true"><BellOff size={18}/><span>Тишина включена</span></div>
<span className="closing-spark closing-spark-left" aria-hidden="true">✳</span><span className="closing-spark closing-spark-right" aria-hidden="true">✳</span>
<div className="closing-content"><b className="mark">✳</b><span className="eyebrow">ВАШЕ ВРЕМЯ — ВАШ РИТМ</span><h2>Сделайте <span className="soft">вдох</span><br/>Начните с <span className="number-chip">главного</span></h2><button className="primary" onClick={start}>Мои 25 минут <ArrowRight size={18}/></button><small className="closing-caption"><i/> Спокойный режим уже готов</small></div>
</section></main><footer><a className="brand" href="#"><b>✳</b> тихо</a><span>Место, где можно сосредоточиться.</span><a href="#">Наверх ↑</a><small>© Тихо, 2026 · Концепт</small></footer></>}



