'use client';

/* oxlint-disable jsx-a11y/no-noninteractive-tabindex, jsx-a11y/prefer-tag-over-role -- the review rail needs keyboard focus and its cropped portrait sheet uses accessible background images */

import {useState} from 'react';
import {ArrowRight,Bell,CalendarDays,Check,ChevronDown,CircleCheck,Cloud,FolderKanban,Globe2,Infinity as InfinityIcon,ListTodo,LockKeyhole,MessageCircleMore,Repeat2,Smartphone,TimerReset} from 'lucide-react';

const steps=[
 {number:'01',title:'Соберите всё',text:'Запишите задачи и мысли за несколько секунд. Ничего не нужно держать в голове.',icon:ListTodo},
 {number:'02',title:'Выберите главное',text:'Тихо поможет оставить одну приоритетную задачу и убрать остальное из поля зрения.',icon:CircleCheck},
 {number:'03',title:'Включите фокус',text:'Работайте один спокойный отрезок, сделайте паузу и отметьте результат.',icon:TimerReset},
];
const features=[
 {title:'Проекты и области',text:'Разделяйте работу, личные дела и идеи, сохраняя общий спокойный ритм.',icon:FolderKanban,demo:{label:'ПРОЕКТ',title:'Запуск новой страницы',tag:'Сегодня',items:['Собрать структуру','Проверить тексты'],progress:62}},
 {title:'Сроки и календарь',text:'Видьте неделю целиком и планируйте нагрузку без перегруженных таблиц.',icon:CalendarDays,demo:{label:'КАЛЕНДАРЬ',title:'Спокойная рабочая неделя',tag:'Ср, 14',items:['Созвон с командой','Фокус на макете'],progress:48}},
 {title:'Повторяющиеся задачи',text:'Настройте привычки и регулярные дела один раз.',icon:Repeat2,demo:{label:'РИТУАЛ',title:'Планирование утра',tag:'Каждый день',items:['Выбрать главное','Освободить рабочее место'],progress:76}},
 {title:'Мягкие напоминания',text:'Получайте только те уведомления, которые действительно помогают.',icon:Bell,demo:{label:'ТИШИНА',title:'Уведомления без давления',tag:'Включено',items:['Напомнить перед фокусом','Не беспокоить до 12:30'],progress:88}},
];
const faqs=[
 ['Можно ли пользоваться бесплатно','Да. Бесплатный план включает задачи, проекты и фокус-таймер без ограничения по времени.'],
 ['Где хранятся мои данные','Данные шифруются и синхронизируются между вашими устройствами. Экспорт доступен в любой момент.'],
 ['Работает ли Тихо без интернета','Да. Задачи и таймер доступны офлайн, изменения синхронизируются после подключения.'],
 ['Можно ли подключить календарь','В версии Plus доступны Google Calendar, Apple Calendar и импорт задач из Telegram.'],
];

export function HowItWorks(){return <section id="how" className="how reveal" data-scene aria-labelledby="how-title"><div className="product-heading"><span className="eyebrow">КАК РАБОТАЕТ ТИХО</span><h2 id="how-title">От мысли до результата<br/><span className="soft">в три спокойных шага</span></h2></div><div className="step-grid"><span className="step-line" aria-hidden="true"/>{steps.map(({number,title,text,icon:Icon})=><article className="step" key={number}><span className="step-number">{number}</span><span className="step-icon"><Icon/></span><h3>{title}</h3><p>{text}</p><span className="step-pulse" aria-hidden="true"/></article>)}</div></section>}

export function FeatureSuite(){const [active,setActive]=useState(0);const selected=features[active];return <section id="features" className="feature-suite reveal" data-scene aria-labelledby="features-title"><div className="product-heading split"><div><span className="eyebrow">ВСЁ НУЖНОЕ РЯДОМ</span><h2 id="features-title">Полноценный трекер<br/><span className="soft">без ощущения перегруза</span></h2></div><p>Наведите на возможность<br/>и посмотрите её в действии</p></div><div className="feature-layout"><div className="feature-list">{features.map(({title,text,icon:Icon},i)=><button type="button" className={i===active?'active':''} key={title} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} aria-pressed={i===active}><span><Icon/></span><div><h3>{title}</h3><p>{text}</p></div><em>0{i+1}</em></button>)}</div><div className="live-stage"><span className="stage-orbit one"/><span className="stage-orbit two"/><div className="live-ui" key={selected.title} aria-live="polite"><div className="live-signal"><i/><i/><i/></div><div className="live-top"><span>Моя неделя</span><small>12–18 августа</small></div><div className="week-row">{['ПН','ВТ','СР','ЧТ','ПТ'].map((d,i)=><span className={i===active%5?'active':''} key={d}><small>{d}</small><b>{12+i}</b></span>)}</div><div className="project-chip"><i/><span><small>{selected.demo.label}</small><strong>{selected.demo.title}</strong></span><em>{selected.demo.tag}</em></div><div className="mini-task"><Check size={13}/> {selected.demo.items[0]}</div><div className="mini-task pending"><span/> {selected.demo.items[1]}</div><div className="live-footer"><span>Ваш спокойный прогресс</span><b>{selected.demo.progress}%</b></div></div></div></div></section>}

export function Platforms(){return <section className="platforms reveal" data-scene aria-label="Платформы и интеграции"><div><span className="eyebrow">ВСЕГДА ПОД РУКОЙ</span><h2>Ваши задачи<br/><span className="soft">на каждом устройстве</span></h2><p>Начните на компьютере, продолжите с телефона.<br/>Тихо сохранит контекст и текущий фокус.</p></div><div className="platform-cloud"><span><Globe2/><b>Web</b></span><span><Smartphone/><b>iOS</b></span><span><Smartphone/><b>Android</b></span><span><MessageCircleMore/><b>Telegram</b></span><span><CalendarDays/><b>Calendar</b></span><i><Cloud/> Синхронизировано</i><strong className="orbit-core"><Cloud/><small>ТИХО</small></strong></div></section>}

export function Testimonials(){const reviews=[['Анна Соколова','продуктовый дизайнер','01','−7 переключений в день','Я перестала бесконечно перестраивать списки и наконец начала заканчивать важное'],['Михаил Орлов','руководитель студии','02','+5 часов фокуса','В Тихо достаточно структуры, чтобы не потеряться, и достаточно воздуха, чтобы спокойно работать'],['Лена Юдина','редактор','03','82% задач в срок','Таймер, задачи и статистика в одном ритме. За неделю стало заметно меньше переключений'],['Илья Ветров','иллюстратор','04','12 спокойных дней','План на день перестал выглядеть как наказание. Теперь я вижу один понятный следующий шаг']];return <section className="testimonials reveal" data-scene aria-labelledby="reviews-title"><div className="product-heading split"><div><span className="eyebrow">ТИХИЕ ИСТОРИИ</span><h2 id="reviews-title">Люди возвращают себе<br/><span className="soft">время для важного</span></h2></div><div className="rating"><span>★★★★★</span><strong>4,9</strong><small>оценка участников бета-теста</small></div></div><div className="quote-viewport" tabIndex={0} aria-label="Отзывы пользователей"><div className="quote-grid">{reviews.map(([name,role,index,result,quote],i)=><blockquote key={name} className={`review-card review-${i+1}`}><div className="review-top"><span className={`review-avatar avatar-${i+1}`} role="img" aria-label={`Портрет: ${name}`}/><span><b>{name}</b><small>{role}</small></span><i>{index}</i></div><p>«{quote}»</p><footer><span>Результат с Тихо</span><strong>{result}</strong></footer></blockquote>)}</div></div><small className="swipe-hint">Потяните, чтобы прочитать ещё <ArrowRight/></small></section>}

export function Pricing(){return <section id="pricing" className="pricing reveal" data-scene aria-labelledby="pricing-title"><div className="product-heading"><span className="eyebrow">ПРОСТЫЕ ТАРИФЫ</span><h2 id="pricing-title">Начните бесплатно<br/><span className="soft">добавьте больше по мере роста</span></h2></div><div className="price-grid"><article><span className="price-label">ТИХО FREE</span><h3>Бесплатно</h3><p>Для личных задач и спокойного знакомства с методом</p><ul><li><Check/> Задачи и проекты</li><li><Check/> Фокус-таймер</li><li><Check/> Недельная статистика</li></ul><a href="#beta">Попробовать бесплатно <ArrowRight/></a></article><article className="featured"><span className="price-label">ТИХО PLUS <em>ПОПУЛЯРНЫЙ</em></span><h3>299 ₽ <small>в месяц</small></h3><p>Для тех, кто хочет собрать работу и привычки в одном месте</p><ul><li><Check/> Всё из Free</li><li><Check/> Календарь и повторения</li><li><Check/> Синхронизация устройств</li><li><Check/> Telegram и интеграции</li></ul><a href="#beta">Попробовать 14 дней <ArrowRight/></a></article></div></section>}

export function FAQ(){return <section id="faq" className="faq reveal" data-scene aria-labelledby="faq-title"><div><span className="eyebrow">ВОПРОСЫ И ОТВЕТЫ</span><h2 id="faq-title">Всё, что важно<br/><span className="soft">до первого шага</span></h2><p><LockKeyhole/> Ваши задачи принадлежат только вам</p></div><div>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>}

export function BetaSignup(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);return <section id="beta" className="beta reveal" data-scene aria-labelledby="beta-title"><span className="beta-orbit"/><span className="beta-particle p1"/><span className="beta-particle p2"/><span className="beta-particle p3"/><div><span className="eyebrow">РАННИЙ ДОСТУП</span><h2 id="beta-title">Освободите место<br/><span className="soft">для главного</span></h2><p>Оставьте почту и получите приглашение в бета-версию Тихо</p>{sent?<div className="beta-success"><CircleCheck/> Вы в списке. Скоро напишем</div>:<form onSubmit={e=>{e.preventDefault();if(email)setSent(true)}}><label className="sr-only" htmlFor="beta-email">Электронная почта</label><input id="beta-email" required type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button type="submit">Получить доступ <ArrowRight/></button></form>}<small><InfinityIcon/> Бесплатно во время бета-теста</small></div></section>}
